# Generated by Django 4.2.23 on 2025-06-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menuitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=200)),
                ('item_prise', models.IntegerField()),
                ('images/', models.ImageField(upload_to='')),
            ],
        ),
    ]
