# Generated by Django 4.2.23 on 2025-06-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='item_prise',
            new_name='item_price',
        ),
    ]
