# Generated by Django 4.2.23 on 2025-06-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0002_rename_item_prise_menuitem_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='images/',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
