# Generated by Django 4.2.23 on 2025-06-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0003_remove_menuitem_images__menuitem_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
