# Generated by Django 4.2.23 on 2025-06-19 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0006_feedback_itemlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menuitem.itemlist', verbose_name='item_list'),
        ),
    ]
