# Generated by Django 4.2.23 on 2025-06-23 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menuitem', '0008_menuitem_author_menuitem_created_at_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
