# Generated by Django 4.2.23 on 2025-06-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('percentage', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
