# Generated by Django 4.2.23 on 2025-06-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy_now', '0004_alter_product_image'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='buy_now.product'),
            preserve_default=False,
        ),
    ]
