# Generated by Django 4.2.23 on 2025-06-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='Offer',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
