# Generated by Django 4.2.23 on 2025-06-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_offer_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='Offer',
            new_name='offer',
        ),
    ]
