# Generated by Django 4.2.23 on 2025-06-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_rename_offer_offer_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offer',
        ),
    ]
