# Generated by Django 4.2.23 on 2025-06-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
                ('select_person', models.IntegerField(max_length=5)),
                ('date', models.DateField(max_length=20)),
            ],
        ),
    ]
