# Generated by Django 4.2.23 on 2025-06-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
