# Generated by Django 4.2.23 on 2025-06-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_now', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='new_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
