# Generated by Django 4.2.23 on 2025-06-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_now', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
