# Generated by Django 4.2.23 on 2025-06-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_now', '0005_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer',
        ),
    ]
